name: apple
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  cloud_firestore: ^4.13.6
  firebase_auth: ^4.15.3
  firebase_core: ^2.24.0
  firebase_messaging: ^14.7.9
  flutter:
    sdk: flutter
  flutter_animate: ^4.3.0
  flutter_local_notifications: ^16.3.0
  flutter_screenutil: ^5.9.0
  flutter_slidable: ^3.0.1
  flutter_svg: ^2.0.9
  permission_handler: ^11.0.1
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  fonts: 
   - family: Poppins
     fonts:
      - asset: assets/Poppins-Thin.ttf
        weight: 100
      - asset: assets/Poppins-ExtraLight.ttf
        weight: 200  
      - asset: assets/Poppins-Light.ttf
        weight: 300  
      - asset: assets/Poppins-Regular.ttf
        weight: 400  
      - asset: assets/Poppins-Medium.ttf
        weight: 500  
      - asset: assets/Poppins-SemiBold.ttf
        weight: 600 
      - asset: assets/Poppins-Bold.ttf
        weight: 700 
      - asset: assets/Poppins-ExtraBold.ttf
        weight: 800              
  uses-material-design: true
  assets:
   - assets/
