name: apple
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  firebase_core: ^2.24.0
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  fonts: 
   - family: Poppins
     fonts:
      - asset: assets/Poppins-Thin.ttf
        weight: 100
      - asset: assets/Poppins-ExtraLight.ttf
        weight: 200  
      - asset: assets/Poppins-Light.ttf
        weight: 300  
      - asset: assets/Poppins-Regular.ttf
        weight: 400  
      - asset: assets/Poppins-Medium.ttf
        weight: 500  
      - asset: assets/Poppins-SemiBold.ttf
        weight: 600 
      - asset: assets/Poppins-Bold.ttf
        weight: 700 
      - asset: assets/Poppins-ExtraBold.ttf
        weight: 800              
  uses-material-design: true
  assets:
   - assets/
